<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>67ebe295-3653-4ed3-a9fb-3ac4a8bc5b59</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\03.EndPoints\BlazorApp1\BlazorApp1\BlazorApp1.csproj" />
    <ProjectReference Include="..\WebApplication1\WebApplication1.csproj" />
  </ItemGroup>

</Project>
